---
# tasks file for ansible-role-phpcs
- name: get composer bin path
  become: yes
  become_user: "{{ phpcs_user }}"
  command: composer global config bin-dir --absolute
  register: phpcs_composer_bin_path
  check_mode: no
  changed_when: False

- name: install with composer
  become: yes
  become_user: "{{ phpcs_user }}"
  command: >
    composer global require "squizlabs/php_codesniffer=@stable"
    creates={{ phpcs_composer_bin_path.stdout }}/phpcs

- name: setting configs
  become: yes
  become_user: "{{ phpcs_user }}"
  command: "{{ phpcs_composer_bin_path.stdout }}/phpcs --config-set {{ item }}"
  with_items: "{{ phpcs_config_set }}"
