---
# tasks file for ansible-role-phpcs
- name: PHPCS | install with composer
  shell: >
    composer global require "squizlabs/php_codesniffer=@stable"
    creates=~/.composer/vendor/bin/phpcs

- name: PHPCS | check phpcs config
  shell: ~/.composer/vendor/bin/phpcs --config-show
  register: phpcs_config
  ignore_errors: true
  changed_when: false

- name: PHPCS | set encoding to utf8 if not set
  shell: ~/.composer/vendor/bin/phpcs --config-set encoding utf-8
  when: phpcs_config.stdout.find('encoding') == -1
  
- name: PHPCS | set colors to true if not set
  shell: ~/.composer/vendor/bin/phpcs --config-set colors 1
  when: phpcs_config.stdout.find('colors') == -1

- name: PHPCS | set report_width to 120 if not set
  shell: ~/.composer/vendor/bin/phpcs --config-set report_width 120
  when: phpcs_config.stdout.find('report_width') == -1